!macro LONGEDIT_REGISTER_OPENWITH EXT
  ReadRegStr $R0 SHELL_CONTEXT "Software\Classes\.${EXT}" "LongEdit.Markdown_backup"
  ${If} $R0 == ""
    DeleteRegValue SHELL_CONTEXT "Software\Classes\.${EXT}" ""
  ${Else}
    WriteRegStr SHELL_CONTEXT "Software\Classes\.${EXT}" "" "$R0"
  ${EndIf}
  WriteRegStr SHELL_CONTEXT "Software\Classes\.${EXT}\OpenWithProgids" "LongEdit.Markdown" ""
!macroend

!macro LONGEDIT_REMOVE_OPENWITH EXT
  DeleteRegValue SHELL_CONTEXT "Software\Classes\.${EXT}\OpenWithProgids" "LongEdit.Markdown"
  DeleteRegKey /ifempty SHELL_CONTEXT "Software\Classes\.${EXT}\OpenWithProgids"
  DeleteRegValue SHELL_CONTEXT "Software\Classes\.${EXT}" "LongEdit.Markdown_backup"
!macroend

!macro LONGEDIT_REMOVE_RUNTIME_CANDIDATE EXT
  DeleteRegValue HKCU "Software\Classes\.${EXT}\OpenWithProgids" "LongEdit.ExternalFile"
  DeleteRegKey /ifempty HKCU "Software\Classes\.${EXT}\OpenWithProgids"
!macroend

!macro NSIS_HOOK_POSTINSTALL
  !insertmacro LONGEDIT_REGISTER_OPENWITH "md"
  !insertmacro LONGEDIT_REGISTER_OPENWITH "markdown"
!macroend

!macro NSIS_HOOK_POSTUNINSTALL
  !insertmacro LONGEDIT_REMOVE_OPENWITH "md"
  !insertmacro LONGEDIT_REMOVE_OPENWITH "markdown"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "avi"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "avif"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "bash"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "bmp"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "c"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "canvas"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cc"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cfg"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cjs"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "conf"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cpp"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cs"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "css"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "csv"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cts"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "cxx"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "dio"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "docx"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "drawio"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "editorconfig"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "env"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "env.development"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "env.local"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "env.production"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "env.test"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "gif"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "gitignore"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "go"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "h"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "hpp"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "htm"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "html"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "ico"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "ini"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "java"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "jpeg"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "jpg"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "js"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "json"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "jsonc"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "jsx"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "kt"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "kts"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "less"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "log"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "m4v"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "md"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mermaid"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mjs"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mkv"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mmd"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mov"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mp4"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mpeg"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mpg"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "mts"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "odp"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "ods"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "ogv"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "opml"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "pdf"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "png"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "pptx"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "properties"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "ps1"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "py"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "rs"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "scss"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "sh"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "sql"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "svg"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "table.json"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "toml"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "ts"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "tsv"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "tsx"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "txt"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "vue"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "webm"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "webp"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "xlsx"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "xml"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "yaml"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "yml"
  !insertmacro LONGEDIT_REMOVE_RUNTIME_CANDIDATE "zsh"
  DeleteRegKey HKCU "Software\Classes\LongEdit.ExternalFile"
  DeleteRegKey HKCU "Software\LongEdit\Capabilities"
  DeleteRegKey /ifempty HKCU "Software\LongEdit"
  DeleteRegValue HKCU "Software\RegisteredApplications" "LongEdit"
!macroend
